docker-compose.yml, public/.env, public/config/packages/doctrine.yaml
Correction du problème qui empêchait la bdd postgre de se connecter
=> MERGE : fix/docker_bdd into dev

public/assets/css/app.scss, public/package.json, public/webpack.config.js, public/yarn.lock
Add bootstrap template into project
=> MERGE: feat/bootstrap into dev

public/composer.lock, public/config/packages/security.yaml, public/src/Security/LoginFormAuthenticator.php, public/templates/front/security/login.html.twig
=> MERGE: feat/auth into dev

public/src/Controller/Front/EventController.php
=> MERGE: autocomplete-entrant into dev

public/src/Controller/Back/AddressController.php, public/src/Controller/Back/EntrantController.php, public/src/Controller/Back/EventController.php, public/src/Controller/Back/UserController.php, public/src/Controller/Front/EventController.php, public/src/Entity/Address.php, public/src/Entity/Entrant.php, public/src/Entity/Event.php, public/src/Entity/User.php, public/templates/page/operations.html.twig
Ajout des traits et des slug et adaptation des controller pour que ce soit pris en compte
=> MERGE: feat/traits_and_slug into dev

public/src/Security/LoginFormAuthenticator.php
Description : 
Fix sur la redirection après une authentification réussi
=> MERGE: fix:login into dev 

public/src/Controller/Back/EventController.php, public/src/Form/EventType.php
Résolution du problème, on ne pouvait pas ajouter d'event car le formulaire etait incorrect
ajout d'une option back dans le EventType
=> MERGE: fix/eventBack into dev

public/src/Controller/Back/AddressController.php, public/src/Controller/Back/EntrantController.php, public/src/Controller/Back/EventController.php, public/src/Controller/Back/ModulesController.php, public/src/Controller/Back/UserController.php, public/src/Entity/Event.php, public/src/Entity/Modules.php, public/src/Form/EventType.php, public/src/Form/ModulesType.php, public/src/Form/UserType.php, public/src/Repository/ModulesRepository.php, public/src/Service/Modules/BetModuleHelper.php, public/src/Service/Modules/ModulesInterface.php, public/src/Service/ModulesHelper.php, public/templates/back/event/edit.html.twig, public/templates/back/modules/_form.html.twig, public/templates/back/modules/edit.html.twig, public/templates/back/modules/index.html.twig, public/templates/back/modules/new.html.twig, public/templates/back/modules/show.html.twig, public/templates/front/event/_form.html.twig, public/templates/front/event/index.html.twig, public/templates/front/event/show.html.twig, public/templates/page/header.html.twig
=> MERGE: feat/modules into dev

public/src/Command/CreateUserCommand.php, public/src/Command/PromoteUserCommand.php
Ajout commande : promote et create user
=> MERGE: feat/command into dev

public/assets/css/app.scss, public/assets/js/app.js, public/package.json, public/src/Controller/Front/SecurityController.php, public/src/Security/LoginFormAuthenticator.php, public/templates/front/security/login.html.twig, public/templates/page/messages.html.twig
add notification with izitoast for login and register.
Succes and error notifications
=> MERGE: Feat/izitoast into dev

public/src/Controller/Front/SecurityController.php
Modification du controller qui permet l'inscription afin d'authentifier automatiquement après l'inscription
=> MERGE: Feat/auto login into dev

public/assets/js/moduleTournament.js, public/package-lock.json, public/src/Controller/Modules/TournamentModuleController.php, public/src/Service/ModulesHelper.php, public/templates/Modules/ModuleTournament/new.html.twig, public/templates/Modules/base.html.twig
ajout d'un parametre `ajax` dans la vue twig pour éviter de répeter le titre et les div qui contienne le formulaire
=> MERGE Fix/module tournament into dev

public/assets/js/Search.js, public/assets/js/eventList.js, public/assets/js/helper.js, public/src/Controller/Front/EventController.php, public/src/Repository/EventRepository.php, public/templates/front/event/_list.html.twig, public/templates/front/event/index.html.twig, public/webpack.config.js
Ajout d'un filtre sur les événements avec une librairie js qui permet de faire une recherche facilement
=> MERGE Feat/event list filter into dev

public/config/packages/security.yaml, public/src/Controller/Front/EventController.php, public/src/Security/EventVoter.php
=> PR: feat/voters into dev

public/assets/js/app.js, public/src/Controller/Front/EventController.php, public/src/Repository/EventRepository.php, public/templates/front/event/show.html.twig, public/templates/page/modalCancelRegisterEvent.html.twig, public/templates/page/modalRegisterEvent.html.twig
Ajout de l'inscription à un événement pour un utilisateur inscrit sur l'événement de son choix
Si l'utilisateur est inscrit pour l'événement il aura la possibilité de se désinscrire
=> MERGE: Feat/public event register into dev

public/src/Controller/Front/EventController.php
Signed-off-by: Luffy <kosseyla.hamouche@gmail.com>
fix l'email du user lors de son inscription sur un événement. (mail obligatoire)
=> fix/playerRegister : auto set email for public event registration

public/src/Twig/AppExtension.php, public/templates/Modules/ModuleTournament/matches.html.twig, public/templates/Modules/ModuleTournament/show.html.twig
=> Merge Twig v2 into dev

public/assets/js/Search.js, public/src/Controller/Front/EventController.php, public/templates/base.html.twig, public/templates/front/default/index.html.twig, public/templates/front/event/_list.html.twig, public/templates/front/event/index.html.twig, public/templates/front/event/show.html.twig, public/templates/page/footer.html.twig, public/templates/page/header.html.twig, public/templates/page/return.html.twig
=> PR: feat/global-front into dev

public/assets/js/Search.js, public/src/Controller/Front/EventController.php, public/templates/base.html.twig, public/templates/front/default/index.html.twig, public/templates/front/event/_list.html.twig, public/templates/front/event/index.html.twig, public/templates/front/event/show.html.twig, public/templates/page/footer.html.twig, public/templates/page/header.html.twig, public/templates/page/return.html.twig
=> PR: dev into preprod

public/templates/Modules/ModuleTeam/new.html.twig, public/templates/Modules/ModuleTeam/show.html.twig, public/templates/Modules/ModuleTournament/new.html.twig, public/templates/page/operations.html.twig
=> merge hotfix in master

public/src/DataFixtures/ModulesFixtures.php
=> fixtures: change module init order

public/templates/Modules/ModuleTeam/show.html.twig, public/templates/Modules/ModuleTournament/matches.html.twig
=> hotfix: fix front issues

public/assets/js/formEvent.js, public/templates/front/event/_form.html.twig
=> event-entrants: Manage event entrants front

public/templates/front/profile/index.html.twig, public/templates/page/header.html.twig
=> profile-front: Manage profile front

public/templates/front/event/show.html.twig
=> address-map: Add google map iframe into address panel

public/src/Controller/Front/EventController.php, public/src/Controller/Front/ProfileController.php, public/src/Form/ModuleTeamInformationType.php, public/src/Repository/EntrantRepository.php, public/src/Repository/UserRepository.php
=> query-builder: Fix issue about query builder wrong use

public/src/Controller/Front/EventController.php, public/src/Repository/EntrantRepository.php, public/templates/front/event/show.html.twig, public/templates/page/modalCancelRegisterEvent.html.twig
=> fix/register : fix registration for entrant
